name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/nfsd
    - name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/nfsd
    - name: docker push readme
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{secrets.DOCKER_USER}}/nfsd
